require("plugin_config.colorscheme")
require("plugin_config.lualine")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.completions")
require("plugin_config.mason")
require("plugin_config.lsp")
require("plugin_config.gitsigns")
require("plugin_config.oil")
require("plugin_config.markdown_preview")
require("plugin_config.nvimtree")
require("plugin_config.vimwiki")
require("plugin_config.rust")
require("plugin_config.dap")
require("plugin_config.zen_mode")
require("plugin_config.hop")
require("plugin_config.trouble")

-- Not currently using
require("plugin_config.vim-test")
-- require("plugin_config.auto_session")
-- require("plugin_config.copilot")
