require("plugin_config.colorscheme")
require("plugin_config.lualine")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.completions")
require("plugin_config.mason")
require("plugin_config.lsp")
require("plugin_config.gitsigns")
require("plugin_config.oil")
require("plugin_config.markdown_preview")
require("plugin_config.nvimtree")
require("plugin_config.rust")
require("plugin_config.dap")
require("plugin_config.zen_mode")
require("plugin_config.twilight")
require("plugin_config.hop")
require("plugin_config.quickfix")
require("plugin_config.neorg")
require("plugin_config.harpoon")
require("plugin_config.which_key")
require("plugin_config.scratch")
require("plugin_config.leap")

-- Not currently using
require("plugin_config.vim-test")
require("plugin_config.copilot")
